# Global Settings 
setw -g mouse on
set -g status off
set -g prefix C-s

### Pane Settings 
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %
# Pane movement
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R


